analytics: {}
color:
  brandColors:
    - '#9898C8'
    - '#283090'
    - '#5860A8'
    - '#F8F000'
    - '#F8F878'
  brandStrength: 0.9009
  lightness: 0.34009
  rhythmicContrast: 0.558558
  saturation: 0.746621
cta: {}
layout_spectrum: 1
name: Colorado Blue
opengraph: {}
purpose: {}
typography_spectrum: 0.261261
